Fix App crash while opening zoom meetings on non-zoom ingrated app (#359)
- Zoom plugin may or may not be enabled on app. So while invoking the method to open zoom meeting, if the plugin was not added, then it make the app crash by throwing NoClassDefFoundError. So handled this error in SDK side by displaying the appropriate message instead of app crash.